unstable_features = true

format_code_in_doc_comments = true
format_strings = true
imports_layout = "HorizontalVertical"
merge_imports = true
normalize_comments = true
reorder_impl_items = true
use_field_init_shorthand = true
wrap_comments = true
