[package]
name = "server"
version = "0.1.0"
authors = ["Simon Berger <simon@siku2.io>"]
edition = "2018"

[dependencies]
log = "0.4"
rocket = "0.4"
serde = "1.0"
serde_json = "1.0"
tempdir = "0.3"
thiserror = "1.0"
